//! Application state machines built on `statig`.
//!
//! Two state machines manage the app's top-level modes:
//!
//! 1. `VoiceMachine` — models voice input lifecycle:
//!    ```text
//!    Disabled ←→ Enabled (superstate)
//!                    ├── Idle
//!                    ├── Recording  [entry: start capture, exit: stop capture]
//!                    ├── Transcribing
//!                    ├── Done(text)
//!                    └── Error(msg)
//!    ```
//!
//! 2. `AppModeMachine` — models top-level display mode:
//!    ```text
//!    Setup → Dashboard
//!    ```
//!
//! Each state machine lives in its own submodule so that the `State` and
//! `Superstate` types generated by the `#[state_machine]` macro do not
//! collide. Users import the submodule types directly:
//!
//! ```rust,ignore
//! use state_machine::voice_sm::{VoiceMachine, VoiceEvent, State as VoiceState};
//! use state_machine::app_mode_sm::{AppModeMachine, AppModeEvent, State as AppModeState};
//! ```

pub mod voice_sm;
pub mod app_mode_sm;

// Re-export the commonly used items for convenience.
pub use voice_sm::{VoiceMachine, VoiceEvent};
pub use app_mode_sm::{AppModeMachine, AppModeEvent};
